image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
    - echo 'www.aleksanderveriksen.no' > public\CNAME
    - git config --global user.email "eriksen1998@live.no"
    - git config --global user.name "Aleksander"
    - git add public
    - git commit -m "Deploy to GitHub Pages"
    - git push origin `git subtree split --prefix public HEAD`:gh-pages --force
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
