name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'  # Specify the Node.js version you need

      - name: Check Node.js version # Check
        run: node -v

      - name: Install dependencies # Install
        run: npm install

      - name: List installed packages
        run: npm list --depth=0

      - name: Build the project
        run: npm run build  # Adjust this command based on your project setup

      - name: Copy build files to public directory
        run: cp -a dist/. public/  # Adjust this if your build output is in a different directory

      - name: Create CNAME file
        run: echo 'www.aleksanderveriksen.com' > public/CNAME  # Replace with your custom domain
      
      # Email if fail
      - name: Configure Git
        run: |
          git config --global user.email "eriksen1998@live.no"  
          git config --global user.name "Aleksander" 
      # Deploy  
      - name: Deploy to GitHub Pages
        run: |
          git add public
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AleksanderVEriksen/React-React_portfolio.git `git subtree split --prefix public HEAD`:gh-pages --force